name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration